export const projects = [
  {
    title: "Finhub",
    alt: "Finhub / Google Finance Clone Project Image",
    description: "finance app",
    technologies:
      "React, TypeScript, ReCharts, Node.js, ExpressJS, and MongoDB",
    images: [
      "src/assets/finhub/finhub1.png",
      "src/assets/finhub/finhub2.png",
      "src/assets/finhub/finhub3.png",
      "src/assets/finhub/finhub5.png",
      "src/assets/finhub/finhub6.png",
      "src/assets/finhub/finhub7.png",
      "src/assets/finhub/finhub8.png",
    ],
  },
  {
    title: "Zwitter",
    alt: "Zwitter / Twitter Clone Project Image",
    description: "Twitter clone",
    technologies:
      "React, NextJS, TypeScript, Prisma, TailwindCSS, Zustand, and MongoDB",
    images: [
      "src/assets/zwitter/zwitter1.1.png",
      "src/assets/zwitter/zwitter1.2.png",
      "src/assets/zwitter/zwitter1.3.png",
      "src/assets/zwitter/zwitter1.4.png",
    ],
  },
  {
    title: "Blogs Web App",
    alt: "Blogs Application Project Image",
    description:
      "Create, like, comment, edit, and delete blogs. See other users blogs.",
    technologies: "React, TypeScript, Node.js, ExpressJS, MongoDB",
    images: [
      "src/assets/blogs/blogs1.png",
      "src/assets/blogs/blogs2.png",
      "src/assets/blogs/blogs3.png",
      "src/assets/blogs/blogs4.png",
      "src/assets/blogs/blogs5.png",
    ],
  },
  {
    title: "Library Web App",
    alt: "Library Web App Project Image",
    description: "Add your favorite books to the library",
    technologies: "React, Node.js, ExpressJS, and MongoDB",
    images: [
      "src/assets/library/library1.png",
      "src/assets/library/library2.png",
      "src/assets/library/library3.png",
      "src/assets/library/library4.png",
      "src/assets/library/library5.png",
    ],
  },
  {
    title: "Old Portfolio Website",
    alt: "Old Portfolio Website Project Image",
    description: "Old Portfolio Website",
    technologies: "React, Framer Motion, SCSS, Sanity",
    images: [
      "src/assets/oldportfolio/portfolio1.png",
      "src/assets/oldportfolio/portfolio2.png",
    ],
  },
  {
    title: "Inflation Calculator",
    alt: "Inflation Calculator Project Image",
    description:
      "See how purchasing power of the dollar has changed since 1913!",
    technologies: "React and TailwindCSS",
    images: [
      "src/assets/inflationCalculator/calculator1.png",
      "src/assets/inflationCalculator/calculator2.png",
    ],
  },
  {
    title: "Old Finhub",
    alt: "Old Finhub Project Image",
    description:
      "Get quotes on your favorite stocks, add stocks to your watchlist, get news, and charts",
    technologies: "React, Bootstrap, and RapidAPI",
    images: [
      "src/assets/oldfinhub/oldfinhub1.png",
      "src/assets/oldfinhub/oldfinhub2.png",
      "src/assets/oldfinhub/oldfinhub3.png",
      "src/assets/oldfinhub/oldfinhub4.png",
      "src/assets/oldfinhub/oldfinhub5.png",
      "src/assets/oldfinhub/oldfinhub6.png",
    ],
  },
  {
    title: "Snake",
    alt: "Snake Game Project Image",
    description: "Play the classic game snake",
    technologies: "JavaScript",
    images: ["src/assets/snake/snake.png"],
  },
  {
    title: "Phonebook",
    alt: "Phonebook Project Image",
    description: "Add to the phonebook",
    technologies: "ReactJS, NodeJS, ExpressJS, and MongoDB",
    images: ["src/assets/phonebook/phonebook.png"],
  },
  {
    title: "Appointment Web App",
    alt: "Appointment Web App Project Image",
    description: "Add or remove appointments. Filter the list.",
    technologies: "ReactJS",
    images: ["src/assets/apts/apts.png"],
  },
  {
    title: "Pagination",
    alt: "Pagination Project Image",
    description: "Table that uses pagination, filtering, and search.",
    technologies: "ReactJS",
    images: ["src/assets/pagination/pagination.png"],
  },
  {
    title: "Shiftbid",
    alt: "Shiftbid Project Image",
    description: "Rank your preferred shifts.",
    technologies: "ReactJS",
    images: ["src/assets/shiftbid/shiftbid.png"],
  },
  {
    title: "Todo",
    alt: "Todo Web App Project Image",
    description: "Todo web app",
    technologies: "ReactJS",
    images: ["src/assets/todo/todo.png"],
  },
  {
    title: "Notes",
    alt: "Notes Web App Project Image",
    description: "Notes full-stack app",
    technologies: "ReactJS, NodeJS, ExpressJS, and MongoDB",
    images: ["src/assets/notes/notes.png"],
  },
  {
    title: "Links",
    alt: "Links Web App Project Image",
    description: "Link CRUD app",
    technologies: "ReactJS",
    images: ["src/assets/links/links.png"],
  },
];
