export const projects = [
  {
    title: "Finhub",
    alt: "Finhub / Google Finance Clone Project Image",
    description:
      "Get quotes, charts, and news. Create your profile to add to your watchlists and portfolios.",
    technologies:
      "React, TypeScript, ReCharts, Node.js, ExpressJS, and MongoDB",
    images: [
      "src/assets/finhub/newfin1.png",
      "src/assets/finhub/newfin2.png",
      "src/assets/finhub/newfin3.png",
      "src/assets/finhub/newfin4.png",
      "src/assets/finhub/newfin5.png",
      "src/assets/finhub/newfin6.png",
      "src/assets/finhub/newfin7.png",
      "src/assets/finhub/newfin8.png",
      "src/assets/finhub/newfin9.png",
      "src/assets/finhub/newfin10.png",
      "src/assets/finhub/newfin11.png",
    ],
    link: "https://fin-server-q3o4.onrender.com/",
    github: "https://github.com/CadenceElaina/fin-client",
  },
  {
    title: "Zwitter",
    alt: "Zwitter / Twitter Clone Project Image",
    description: "Twitter clone",
    technologies:
      "React, NextJS, TypeScript, Prisma, TailwindCSS, Zustand, and MongoDB",
    images: [
      "src/assets/zwitter/zwitter1.1.png",
      "src/assets/zwitter/zwitter1.2.png",
      "src/assets/zwitter/zwitter1.3.png",
      "src/assets/zwitter/zwitter1.4.png",
    ],
    link: "https://zwitter-drab.vercel.app/",
    github: "https://github.com/CadenceElaina/zwitter",
  },
  {
    title: "Blogs Web App",
    alt: "Blogs Application Project Image",
    description:
      "Create, like, comment, edit, and delete blogs. See other users blogs.",
    technologies: "React, TypeScript, Node.js, ExpressJS, MongoDB",
    images: [
      "src/assets/blogs/blogs1.png",
      "src/assets/blogs/blogs2.png",
      "src/assets/blogs/blogs3.png",
      "src/assets/blogs/blogs4.png",
      "src/assets/blogs/blogs5.png",
    ],
    link: "https://bloglist-17lz.onrender.com/",
    github: "https://github.com/CadenceElaina/bloglist",
  },
  {
    title: "Library Web App",
    alt: "Library Web App Project Image",
    description: "Add your favorite books to the library",
    technologies: "React, Node.js, ExpressJS, and MongoDB",
    images: [
      "src/assets/library/library1.png",
      "src/assets/library/library2.png",
      "src/assets/library/library3.png",
      "src/assets/library/library4.png",
      "src/assets/library/library5.png",
    ],
    link: "https://library-grapql.netlify.app/",
    github: "https://github.com/CadenceElaina/library-client",
  },
  {
    title: "Old Portfolio Website",
    alt: "Old Portfolio Website Project Image",
    description: "Old Portfolio Website",
    technologies: "React, Framer Motion, SCSS, Sanity",
    images: [
      "src/assets/oldportfolio/portfolio1.png",
      "src/assets/oldportfolio/portfolio2.png",
    ],
    link: "https://cadenceelaina.netlify.app/",
    github: "https://github.com/CadenceElaina/portfolio_react_sanity",
  },
  {
    title: "Inflation Calculator",
    alt: "Inflation Calculator Project Image",
    description:
      "See how purchasing power of the dollar has changed since 1913!",
    technologies: "React and TailwindCSS",
    images: [
      "src/assets/inflationCalculator/calculator1.png",
      "src/assets/inflationCalculator/calculator2.png",
    ],
    link: "https://inflationcalculator.netlify.app/",
    github:
      "https://github.com/CadenceElaina/inflation_calculator_react_tailwind",
  },
  {
    title: "Old Finhub",
    alt: "Old Finhub Project Image",
    description:
      "Get quotes on your favorite stocks, add stocks to your watchlist, get news, and charts",
    technologies: "React, Bootstrap, and RapidAPI",
    images: [
      "src/assets/oldfinhub/oldfinhub1.png",
      "src/assets/oldfinhub/oldfinhub2.png",
      "src/assets/oldfinhub/oldfinhub3.png",
      "src/assets/oldfinhub/oldfinhub4.png",
      "src/assets/oldfinhub/oldfinhub5.png",
      "src/assets/oldfinhub/oldfinhub6.png",
    ],
    link: "https://finhub-financeapp.netlify.app/",
    github: "https://github.com/CadenceElaina/finance-app/tree/main",
  },
  {
    title: "Snake",
    alt: "Snake Game Project Image",
    description: "Play the classic game snake",
    technologies: "JavaScript",
    images: ["src/assets/snake/snake.png"],
    link: "https://snakevanillajs.netlify.app/",
    github: "https://github.com/CadenceElaina/JavaScript-Snake-Game",
  },
  {
    title: "Phonebook",
    alt: "Phonebook Project Image",
    description: "Add to the phonebook",
    technologies: "ReactJS, NodeJS, ExpressJS, and MongoDB",
    images: ["src/assets/phonebook/phonebook.png"],
    link: "https://phonebook-fullstack-1z2c.onrender.com/",
    github: "https://github.com/CadenceElaina/phonebook-fullstack",
  },
  {
    title: "Appointment Web App",
    alt: "Appointment Web App Project Image",
    description: "Add or remove appointments. Filter the list.",
    technologies: "ReactJS",
    images: ["src/assets/apts/apts.png"],
    link: "https://manageyourappointments.netlify.app/",
    github: "https://github.com/CadenceElaina?page=1&tab=repositories",
  },
  {
    title: "Pagination",
    alt: "Pagination Project Image",
    description: "Table that uses pagination, filtering, and search.",
    technologies: "ReactJS",
    images: ["src/assets/pagination/pagination.png"],
    link: "https://tablewithpagination-search-asc-dsc.netlify.app/",
    github: "https://github.com/CadenceElaina/task1-react?tab=readme-ov-file",
  },
  {
    title: "Shiftbid",
    alt: "Shiftbid Project Image",
    description: "Rank your preferred shifts.",
    technologies: "ReactJS",
    images: ["src/assets/shiftbid/shiftbid.png"],
    link: "https://shiftbid.netlify.app/",
    github: "https://github.com/CadenceElaina/shiftbid",
  },
  {
    title: "Todo",
    alt: "Todo Web App Project Image",
    description: "Todo web app",
    technologies: "ReactJS",
    images: ["src/assets/todo/todo.png"],
    link: "https://thegreatestmostoriginaltodoapp.netlify.app/",
    github: "https://github.com/CadenceElaina/todo_app",
  },
  {
    title: "Notes",
    alt: "Notes Web App Project Image",
    description: "Notes full-stack app",
    technologies: "ReactJS, NodeJS, ExpressJS, and MongoDB",
    images: ["src/assets/notes/notes.png"],
    link: "https://notes-app-57bk.onrender.com/",
    github: "https://github.com/CadenceElaina/notes-app",
  },
  {
    title: "Links",
    alt: "Links Web App Project Image",
    description: "Link CRUD app",
    technologies: "ReactJS",
    images: ["src/assets/links/links.png"],
    link: "https://yourlinks.netlify.app/",
    github: "https://github.com/CadenceElaina/Link-App",
  },
];
